### ISSUE TITLE
m5stickc microphone issues.

### ISSUE THREAD

**Issue by hediondo1** [atuline/WLED#135] opened 2021-11-11 20:47 UTC
**Take a look at the wiki and FAQ, perhaps your question is already answered!**
[FAQ](https://github.com/Aircoookie/WLED/wiki/FAQ)

**Please consider asking your question on the WLED forum or Discord**
[Forum](https://wled.discourse.group/)
[Discord](https://discord.gg/KuqP7NE)
[What to post where?](https://github.com/Aircoookie/WLED/issues/658)

**If you do not like to use these platforms, delete this template and ask away!**
Please keep in mind though that the issue section is generally not the preferred place for general questions.

**Comment by hediondo1** [comment] 2021-11-11 20:52
anyone tryed to make work m5stickc mic? i´m unable to make it work. i achieved m5 atom matrix with both matrix and external led simultaneous and external analog mic but m5stickc not working with mic.

**Comment by FHeilmann** [comment] 2021-11-15 13:45
Unfortunately the mic on the m5stickc is a PDM i2s microphone, which is currently not supported by WLED-SR

**Comment by FHeilmann** [comment] 2021-12-31 14:16
@hediondo1 please do give the latest `dev` branch a try. I added pdm i2s microphone support 1-2 weeks ago.

**Comment by hediondo1** [comment] 2022-01-02 23:22
ok i´ll try soon,thanks for your efforts!! good work!!

**Comment by hediondo1** [comment] 2022-01-06 22:31
ok atom echo,atom matrix with embeded matrix +some leds working with digital ext mic.m5stick c working but need to check the screen now.
atom echo works with pdm mic perfect.looks a good choice for soundreactive wled.
next step make stickc full working.

**Comment by claudiosv** [comment] 2022-05-17 20:39
I'm working on getting the M5Stick C to work again in #206 .

**Comment by softhack007** [comment] 2022-06-18 21:33
Hi @hediondo1, did the latest DEV version (with PDM microphone support) work for you? If yes, can we close this issue?

**Comment by softhack007** [comment] 2022-06-28 21:12
WLED dev version supports PDM microphones, and the problem report author confirmed it works for him. Assuming that the problem is solved now.

**Closed by softhack007** 2022-06-28 21:12 UTC
Labels: question
