### ISSUE TITLE
The USB serial port cannot be used normally with Adalight!

### ISSUE THREAD

**Issue by zx804262156** [atuline/WLED#176] opened 2022-02-28 13:07 UTC
The USB serial port cannot be used normally with Adalight!

**Comment by netmindz** [comment] 2022-03-04 00:17
You are just making a statement. This tells us nothing really.

Is this a supported feature of WLED you are referring to? Have you had it working before? If you had it working was that with this sounds reactive fork?
If you have had it working, what was the version number that was on and what versions have you tried that do not work. Which microcontroller are you using?

**Comment by softhack007** [comment] 2022-07-08 20:24
No reaction from problem author since last months, and not enough detail available to reproduce the problem. Closing report.

**Closed by softhack007** 2022-07-08 20:24 UTC
Labels: bug
