### ISSUE TITLE
 ESP8266 binaries not available the latest version on sound reactive

### ISSUE THREAD

**Issue by DJprasenjit** [atuline/WLED#263] opened 2023-01-08 17:05 UTC
i need the 0.13.3 version  ESP8266 binaries for sound reactive . please upload it ASAP

**Comment by netmindz** [comment] 2023-01-08 19:53
ESP8266 is no longer supported and hasn't been for quite a while now

**Comment by softhack007** [comment] 2023-01-08 20:19
duplicate of https://github.com/atuline/WLED/issues/230

**Closed by softhack007** 2023-01-08 20:19 UTC
Labels: enhancement
