### ISSUE TITLE
Analog Microphone (left channel only - 6 cables 5 are soldered ? what is missing ?

### ISSUE THREAD

**Issue by sk2eu** [atuline/WLED#274] opened 2023-09-24 09:29 UTC
ladies and gentlemen ... now I wasted a lot of time to copy a bin under DOS and import to 10 esp32 ... oh everything works only the colors are not displayed full and you can not swap them ... funny ... so again each esp32 fresh flshen by hand and set up ... I really have not found a way until now esp32 bin to read out when they are created ... and then work. 

but to my question ... have not soldered the L/R cable to the esp32 ... but must be so ? or does not need it? 

```
formatting.
**[11:15:17]AS: Analog Microphone (left channel only).**
[11:15:17]Ada
```

![image](https://github.com/atuline/WLED/assets/48036204/e3f93663-ec1f-44e7-88e1-0d20b4ee15a6)

![image](https://github.com/atuline/WLED/assets/48036204/d7d819bb-2040-42c2-8f8b-c662f34c08e9)

Using 'COM12' as serial port.
Connecting....
Detecting chip type... Unsupported detection protocol, switching and trying again...
Connecting....
Detecting chip type... ESP32
Connecting....

Chip Info:
 - Chip Family: ESP32
 - Chip Model: ESP32-D0WDQ5-V3 (revision 3)
 - Number of Cores: 2
 - Max CPU Frequency: 240MHz
 - Has Bluetooth: YES
 - Has Embedded Flash: NO
 - Has Factory-Calibrated ADC: YES
 - MAC Address: 08:sssssss4
Uploading stub...
Running stub...
Stub running...
Changing baud rate to 460800
Changed.
 - Flash Size: 4MB
 - Flash Mode: dio
 - Flash Frequency: 80MHz
Erasing flash (this may take a while)...
Chip erase completed successfully in 2.4s
Flash will be erased from 0x00001000 to 0x00005fff...
Flash will be erased from 0x00008000 to 0x00008fff...
Flash will be erased from 0x0000e000 to 0x0000ffff...
Flash will be erased from 0x00010000 to 0x00149fff...
Flash params set to 0x022f
Compressed 17440 bytes to 12090...
Writing at 0x00001000... (100 %)
Wrote 17440 bytes (12090 compressed) at 0x00001000 in 0.4 seconds (effective 397.8 kbit/s)...
Hash of data verified.
Compressed 3072 bytes to 128...
Writing at 0x00008000... (100 %)
Wrote 3072 bytes (128 compressed) at 0x00008000 in 0.0 seconds (effective 1535.2 kbit/s)...
Hash of data verified.
Compressed 8192 bytes to 47...
Writing at 0x0000e000... (100 %)
Wrote 8192 bytes (47 compressed) at 0x0000e000 in 0.0 seconds (effective 2528.0 kbit/s)...
Hash of data verified.
Compressed 1284464 bytes to 800799...
Writing at 0x00010000... (2 %)
)
Writing at 0x0014437c... (100 %)
Wrote 1284464 bytes (800799 compressed) at 0x00010000 in 18.1 seconds (effective 568.9 kbit/s)...
Hash of data verified.

Leaving...
Hard Resetting...
Hard resetting via RTS pin...
Done! Flashing is complete!

Showing logs:
[11:15:16].pio/libdeps/esp32_4MB_S/LittleFS_esp32/src/lfs.c:1078:warn: Superblock not found (dir pair at {0x0, 0x1}). Filesystem needs formatting.
**[11:15:17]AS: Analog Microphone (left channel only).**
[11:15:17]Ada
[11:15:19]No connection configured. Opening access point WLED-AP
[11:15:19]Init AP interfaces
Serial port closed!

**Comment by softhack007** [comment] 2023-09-24 09:43
Dear @sk2eu I'm sorry for your time, but you might understand that the development team cannot influence how you spend it.

According to the logs you show, WLED-SR is configured for analog mic, however your picture shows IMNP441 which are I2S digital. Also you _must_ connect L/R to GND, don't keep the pin floating.

https://github.com/atuline/WLED/wiki/Sound-Settings

<br/>

Please don't abuse bug reports for asking support question.
Join our [Discord](https://discord.gg/4CQRmfR) to discuss your project with community members, and get support from other users.

Closing as not a bug.

**Closed by softhack007** 2023-09-24 09:43 UTC
Labels: enhancement
