### ISSUE TITLE
Sound Reactive - segments getting lost

### ISSUE THREAD

**Issue by homonto** [atuline/WLED#242] opened 2022-10-25 06:19 UTC
### What happened?

occasionally the segment configuration is lost

### To Reproduce Bug

random

### Expected Behavior

keeps the configuration intact after restart

### Install Method

Binary from WLED.me

### What version of WLED?

 WLED 0.13.0-b6 (build 2112080) and also in WLED 0.13.2 (build 2207301)

### Which microcontroller/board are you seeing the problem on?

ESP32

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by softhack007** [comment] 2022-10-25 06:56
Segments are not stored separately, but they are always part of a preset. It's intended behaviour of WLED.
The benefit is that you can make several segment configurations, for example have one preset that runs "gravimeter" on the complete stripe, and another preset where the top half shows fireworks, while the lower half runs waterfall.

<br/>
The best approach is to configure your preferred segments, then make a preset that is loaded at startup.
See "My Segments are gone after a reboot!" in the WLED FAQ https://kno.wled.ge/basics/faq/


closing, as this is intended behaviour, and not a bug.


Please join our discord to get help and support from the community:
<a href="https://discord.gg/4CQRmfR"><img src="https://discordapp.com/api/guilds/700041398778331156/widget.png?style=banner2" width="30%"  align="middle"></a>
Join Discord to discuss beta testing of our [sound reactive fork](https://discord.gg/4CQRmfR) of WLED. 

<a href="https://discord.gg/KuqP7NE"><img src="https://discordapp.com/api/guilds/473448917040758787/widget.png?style=banner2" width="30%" align="middle"></a>
Join Discord to discuss [AirCookie's WLED](https://discord.gg/KuqP7NE).

**Closed by softhack007** 2022-10-25 06:56 UTC
Labels: bug

**Comment by homonto** [comment] 2022-10-25 07:07
thank you
