### ISSUE TITLE
Segment is not saved

### ISSUE THREAD

**Issue by pafftis** [atuline/WLED#258] opened 2022-12-12 16:44 UTC
### What happened?

Segment is not saved.
I'm trying to create a segment and presets.
After the reboot, presets remain, and all segments disappear. I tried on two different versions of wled

### To Reproduce Bug

I went to the website, there I chose to install esp 32. connected wt32-ethernet and flashed the firmware from esp 32.

### Expected Behavior

After creating a segment, it should remain even after the system is rebooted.

### Install Method

From https://wled-install.github.io/

### What version of Soundreactive WLED?

13.3 and 14b

### Which microcontroller/board are you seeing the problem on?

ESP32

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by softhack007** [comment] 2022-12-12 17:23
Hi, 
> after creating a segment, it should remain even after the system is rebooted.

This looks like a common misunderstanding of how segments work. Segments are part of a preset, so to keep your "favourite segments" you have to create a preset (that includes segment settings), and make this preset the default one to load at startup.

See https://kno.wled.ge/basics/faq/#my-segments-are-gone-after-a-reboot

I'm closing this report, as what you describe is expected behaviour (according to faq).
If you're still experiencing other problems related to segments, please create a bug report in ["upstream" WLED](https://github.com/Aircoookie/WLED/issues/new/choose).

**Closed by softhack007** 2022-12-12 17:23 UTC
Labels: bug
